/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/plans': typeof PlansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/scholarships': typeof ScholarshipsRoute
  '/what-if': typeof WhatIfRoute
  '/plans/$planId': typeof PlansPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/plans': typeof PlansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/scholarships': typeof ScholarshipsRoute
  '/what-if': typeof WhatIfRoute
  '/plans/$planId': typeof PlansPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/plans': typeof PlansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/scholarships': typeof ScholarshipsRoute
  '/what-if': typeof WhatIfRoute
  '/plans/$planId': typeof PlansPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compatibility'
    | '/dashboard'
    | '/documents'
    | '/plans'
    | '/profile'
    | '/scholarships'
    | '/what-if'
    | '/plans/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compatibility'
    | '/dashboard'
    | '/documents'
    | '/plans'
    | '/profile'
    | '/scholarships'
    | '/what-if'
    | '/plans/$planId'
  id:
    | '__root__'
    | '/'
    | '/compatibility'
    | '/dashboard'
    | '/documents'
    | '/plans'
    | '/profile'
    | '/scholarships'
    | '/what-if'
    | '/plans/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompatibilityRoute: typeof CompatibilityRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  PlansRoute: typeof PlansRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  WhatIfRoute: typeof WhatIfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRoute
    }
  }
}

interface PlansRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompatibilityRoute: CompatibilityRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  PlansRoute: PlansRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  WhatIfRoute: WhatIfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
