/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/documents': typeof DocumentsRoute
  '/profile': typeof ProfileRoute
  '/scholarships': typeof ScholarshipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/documents': typeof DocumentsRoute
  '/profile': typeof ProfileRoute
  '/scholarships': typeof ScholarshipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/documents': typeof DocumentsRoute
  '/profile': typeof ProfileRoute
  '/scholarships': typeof ScholarshipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/compatibility' | '/documents' | '/profile' | '/scholarships'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compatibility' | '/documents' | '/profile' | '/scholarships'
  id:
    | '__root__'
    | '/'
    | '/compatibility'
    | '/documents'
    | '/profile'
    | '/scholarships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompatibilityRoute: typeof CompatibilityRoute
  DocumentsRoute: typeof DocumentsRoute
  ProfileRoute: typeof ProfileRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompatibilityRoute: CompatibilityRoute,
  DocumentsRoute: DocumentsRoute,
  ProfileRoute: ProfileRoute,
  ScholarshipsRoute: ScholarshipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
